    - name: check for backup file
      file:
        path: "{{ home }}/backup.jar"
        state: absent
 
    - name: delete the old backup.jar
      command: rm -rf {{ home }}/backup.jar

    - name: create new backup.jar
      command: cp {{ home }}/proj.jar {{ home }}/backup.jar

    - name: copy new jar file to package location
      copy: 
        src: proj.jar 
        dest: "{{ home }}"

    - name: restart the service
      command: /app/{{ item }}/bin/startup.sh  
