    - name: check for backup file
      stat:
        path: "{{ home }}/backup.jar"
        register: result

    - name: delete the backup file if exists
      file:
        path: "{{ home }}/backup.jar"
        state: absent
      when: result.stat.exists

    - name: create new backup.jar
      command: cp {{ home }}/proj.jar {{ home }}/backup.jar

    - name: copy new jar file to package location
      copy: 
        src: proj.jar 
        dest: "{{ home }}"

    - name: restart the service
      command: /app/{{ item }}/bin/startup.sh  
